name: DEV API Tests with Allure Reports

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Run tests on DEV
      run: mvn clean test 
    
    - name: Generate Allure Report
      run: mvn allure:report
    
    - name: Upload Allure report as artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-report-dev
        path: target/site/allure-maven-plugin/
        retention-days: 14
    
    - name: Deploy Allure report to GitHub Pages - DEV
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site/allure-maven-plugin
        destination_dir: dev-reports
