name: MASTER API Tests with Allure Reports

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

# Adicionar permissões ao workflow
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Run tests on QA
      run: mvn clean test 
    
    - name: Generate Allure Report
      run: mvn allure:report
    
    - name: Upload Allure report as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Allure Reports
        path: target/site/allure-maven-plugin/
        retention-days: 90
        if-no-files-found: warn
